title: Akshay Chaudhary (Alexith) # your name (or website title) here
logo: "/images/VAPORGRAM1585659115077.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Developer
  <br>
  Cartoonist
  <br>
  Music producer
  <br>
  Spotify: open.spotify.com/artist/4GMEwNWTi3xbw7DT488Nog 
  <br>
  Apple music: apple.co/2wX5h6b
  <br>
  Album: alexith.bandcamp.com
  <br>
  Support: paypal.me/akshaycy
  <br>
  www.instagram.com/alexithmusic
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
