title: Akshay Chaudhary # your name (or website title) here
logo: "/images/VAPORGRAM1585659115077.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Developer
  <br><br>
  Writer
  <br><br>
  Cartoonist
  <br><br>  
  I use blender for my  2d cartoons.
  <br><br>
  Downtempo music producer @Alexith
  <br><br>
  my music releases on Apple music: 
  <br>
  apple.co/2wX5h6b
  <br><br>
  open.spotify.com/artist/4GMEwNWTi3xbw7DT488Nog 
  <br><br>
  I am a debian linux user
  <br><br>
  www.instagram.com/alexithmusic
  <br><br>
  alexith.bandcamp.com
  <br><br>
  <a href="https://www.linkedin.com/in/akshaycy">LinkedIn</a> 
  Support:<br>
  paypal.me/akshaycy
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
